version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopuser -d shop"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: ./nilanikan-backend
    environment:
      DJANGO_SECRET_KEY: dev-insecure-change-me
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: shop
      DB_USER: shopuser
      DB_PASSWORD: shoppass
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./nilanikan-backend:/app
      - media:/app/media
      - staticfiles:/app/staticfiles

  frontend:
    image: node:20-alpine
    working_dir: /app
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./nilanikan-shop:/app
    command: sh -lc "npm install && HOST=0.0.0.0 npm run dev"
    depends_on:
      - web

volumes:
  pgdata:
  media:
  staticfiles:
