# Generated by Django 4.2.14 on 2025-09-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('product_slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_id', 'is_approved'], name='reviews_rev_product_99e47c_idx'), models.Index(fields=['product_slug', 'is_approved'], name='reviews_rev_product_b2bbdb_idx')],
            },
        ),
    ]
