# Generated by Django 4.2.14 on 2025-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
