# Generated by Django 4.2.14 on 2025-09-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/'),
        ),
        migrations.CreateModel(
            name='BundleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bundles/gallery/')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.bundle')),
            ],
        ),
    ]
