# Generated by Django 4.2.14 on 2025-09-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
