# Generated by Django 4.2.14 on 2025-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bundleimage_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
