# Generated by Django 4.2.14 on 2025-09-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_category_options_category_icon_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('url', models.URLField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='menu/icons/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/images/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('device', models.CharField(choices=[('all', 'All'), ('desktop', 'Desktop'), ('mobile', 'Mobile')], default='all', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='catalog.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
