# Generated by Django 4.2.14 on 2025-09-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
