# Generated by Django 4.2.14 on 2025-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_size_guide_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='default_size_guide_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
