# Generated by Django 4.2.14 on 2025-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_category_default_size_guide_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/size_charts/'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
