# Generated by Django 4.2.14 on 2025-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_size_chart_image_product_size_guide_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_guide_html',
            field=models.TextField(blank=True, db_column='product_size_guide_html', null=True),
        ),
    ]
