# Generated by Django 4.2.14 on 2025-09-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_bundle_image_bundleimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("alt", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="slides/")),
                ("link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="عدد کمتر = جلوتر"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slides",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
