# Generated by Django 4.2.14 on 2025-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order', '-created_at')},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='product',
        ),
        migrations.AlterField(
            model_name='slide',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
